name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "MSG - The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "MSG - This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "MSG - The name of your branch is $ {{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4.1.7
      - run: echo "MSG - The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "MSG - The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "MSG - This job's status is ${{ job.status }}."
